name: vjbus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Functionality & Services
  flutter_background_service: ^5.1.0
  geolocator: ^13.0.2
  permission_handler: ^12.0.0+1
  socket_io_client: ^3.0.2
  android_intent_plus: ^4.0.3
  wakelock_plus: ^1.3.1
  flutter_local_notifications: ^17.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.3

  # UI & UX
  cupertino_icons: ^1.0.8
  vibration: ^3.1.3

  # Extra
  send_to_background: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    # - assets/background_pattern.png
